---
- hosts: "tag_Name_{{ cluster }}"
  become: yes
  remote_user: ubuntu

  pre_tasks:
    - name: Create ext4 fs on second disk
      filesystem: fstype=ext4 dev="{{ instances_device_name }}"
      ignore_errors: yes

    - name: Mount second disk to mount point
      mount: name="{{ es_mount_point }}" src="{{ instances_device_name }}" fstype=ext4 state=mounted

  roles:
    - elasticsearch

  post_tasks:
    - name: Collect list of created instances
      ec2_remote_facts:
        region: "{{ vpc_region }}"
        filters:
          instance-state-name: running
          "tag:Name": "{{ cluster }}"
      register: ec2
    - name: Attach new instances into LB
      ec2_elb:
        instance_id: "{{ item.id }}"
        ec2_elbs: "{{ lb_name }}"
        region: "{{ vpc_region }}"
        state: present
      with_items: "{{ ec2.instances }}"
